### ISSUE TITLE
La guarida de Rlim Shairkoth (The lair of Rlim Shairkoth)

### ISSUE THREAD

**Issue by vidimus** [vidimus/Valkyrie_Mom_scenarios_translations#24]
Translation into Spanish finished. Here are all the needed files.

**Comment by vidimus** [comment]
Newspaper clipping
![dead](https://user-images.githubusercontent.com/41538948/89591908-ac1dc380-d84b-11ea-8880-47ff3be40e8d.png)
![lie](https://user-images.githubusercontent.com/41538948/89591923-af18b400-d84b-11ea-925e-70f685a7f574.png)
![the](https://user-images.githubusercontent.com/41538948/89591932-b50e9500-d84b-11ea-9cc0-90dcb3f0dc9f.png)
![must](https://user-images.githubusercontent.com/41538948/89591926-b17b0e00-d84b-11ea-8575-dc776df0a183.png)

**Comment by vidimus** [comment]
Initial clues:
![tokens](https://user-images.githubusercontent.com/41538948/89838589-e2b94e00-db6b-11ea-8168-095afea9ee05.png)

**Comment by vidimus** [comment]
Translation:
[Localization.Spanish.txt](https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/files/5133064/Localization.Spanish.txt)

**Comment by vidimus** [comment]
And the intro audio:
[annabelle.zip](https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/files/5096559/annabelle.zip)

**Comment by vidimus** [comment]
@Sodapaps Translation is complete right now.

I wish you could upload it soon (that would be a great new about you!).

**Comment by vidimus** [comment]
Updated the Spanish translation (some typos hunted down).

**Comment by scrubbless** [comment]
I'll try to add this later

**Comment by scrubbless** [comment]
Hi @vidimus  I am waiting for the latest version of Litas's Polish translation and then i'll publish both the spanish and polish translations. Please let me know if you have any last minute alterations 😁

**Comment by vidimus** [comment]
> Hi @vidimus I am waiting for the latest version of Litas's Polish translation and then i'll publish both the spanish and polish translations. Please let me know if you have any last minute alterations

Hello, @scrubbless, not at this moment. But, as usual, I will find mistakes or typos as soon as the scenario gets uploaded. Don't worry, I will bother your with new updates... :-P

**Comment by scrubbless** [comment]
Translation has been added, please test this and close the issue :)

**Comment by vidimus** [comment]
Thanks, @scrubbless 

it's seems to be OK. 
Closing this issue.
