### ISSUE TITLE
Bajando por la buhardilla (Down the Attic Hole)

### ISSUE THREAD

**Issue by vidimus** [vidimus/Valkyrie_Mom_scenarios_translations#4]
[Localization.Spanish.txt](https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/files/4333399/Localization.Spanish.txt)

**Comment by vidimus** [comment]
[Bajando por la buhardilla.zip](https://github.com/vidimus/Valkyrie-Mom-scenarios-translations/files/4333416/Bajando.por.la.buhardilla.zip)

**Comment by Hobbeslionheart** [comment]
Added and published

**Comment by vidimus** [comment]
Thanks a lot, @Hobbeslionheart
